services:
  postgres:
    image: postgres:latest
    container_name: postgres_container
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: lmsdb
    ports:
      - "5432:5432"
    volumes:
      - ./database-data:/var/lib/postgresql/data
